name: projectuas
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  email_validator: ^2.1.17
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica-Bold.ttf
        - asset: fonts/Helvetica-BoldOblique.ttf
        - asset: fonts/helvetica-light-587ebe5a59211.ttf
        - asset: fonts/Helvetica-Oblique.ttf
        - asset: fonts/Helvetica.ttf
